image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # для использования своего скрипта сборки

install:
  # запуск SUT (& означает, что в фоновом режиме - не блокируется терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    - sudo apt-get -qq update
    - sudo apt-get install google-chrome-stable > /dev/null

build_script:
  - chmod +x gradlew #  предоставление прав на запуск файла gradlew
  - ./gradlew test --info  # запуск тестов, флаг --info позволяет выводить больше информации
